version: '3.8'

services:
  api:
    image: univent-api
    restart: always
    container_name: univent-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
